#!/bin/bash
s3files=`aws s3 ls ${1} | awk '{if ($4) print $4}'`

(
i=0
for file in $s3files; do
    echo "JOB  ${i} from-s3.submit"
    echo "VARS ${i} from_s3=\"${file}\""
    echo

    i=$((i+1))
done
) >> from-s3.sub.dag

exit 0
